- name: Create a backup cron file 
  cron:
    name: "gitlab-backup"
    cron_file: "gitlab_backup"    
    user: "root"
    weekday: "*"
    month: "*"
    day: "*"
    hour: "02"                      
    minute: "36"
    job: "/usr/bin/docker exec -t gitlab gitlab-backup create CRON=1"
