---
sysctl_hardening_lines:
  - "kernel.kptr_restrict = 2"
  - "kernel.dmesg_restrict = 1"
  - "kernel.randomize_va_space = 2"
  - "kernel.sysrq = 0"

  - "fs.suid_dumpable = 0"
  - "fs.protected_hardlinks = 1"
  - "fs.protected_symlinks = 1"

  - "net.ipv4.ip_forward = 0"
  - "net.ipv4.conf.all.accept_redirects = 0"
  - "net.ipv4.conf.default.accept_redirects = 0"
  - "net.ipv4.conf.all.send_redirects = 0"
  - "net.ipv4.conf.default.send_redirects = 0"
  - "net.ipv4.conf.all.accept_source_route = 0"
  - "net.ipv4.conf.default.accept_source_route = 0"
  - "net.ipv4.conf.all.log_martians = 1"
  - "net.ipv4.conf.default.log_martians = 1"
  - "net.ipv4.icmp_echo_ignore_broadcasts = 1"
  - "net.ipv4.icmp_ignore_bogus_error_responses = 1"
  - "net.ipv4.tcp_syncookies = 1"
  - "net.ipv4.conf.all.rp_filter = 1"
  - "net.ipv4.conf.default.rp_filter = 1"

  - "net.ipv6.conf.all.accept_redirects = 0"
  - "net.ipv6.conf.default.accept_redirects = 0"
  - "net.ipv6.conf.all.accept_source_route = 0"
  - "net.ipv6.conf.default.accept_source_route = 0"
  - "net.ipv6.conf.all.disable_ipv6 = 0"
  - "net.ipv6.conf.default.disable_ipv6 = 0"

auditd_config:
  log_file: "/var/log/audit/audit.log"
  log_format: "RAW"
  flush: "INCREMENTAL_ASYNC"
  freq: 50
  max_log_file: 6
  num_logs: 5
  max_log_file_action: "keep_logs"
  space_left_action: "SYSLOG"
  admin_space_left_action: "SUSPEND"
  action_mail_acct: "root"

legacy_packages_remove:
  - xinetd
  - inetutils-inetd
  - openbsd-inetd
  - rsh-server
  - rsh-redone-server
  - telnetd
  - tftpd-hpa
  - atftpd
  - nis
  - ypserv
  - prelink

passwdqc:
  name: "passwdqc password quality checking"
  default: "yes"
  priority: 1024
  password_type: "Primary"

  retry: 3
  min: ["disabled","disabled","16","12","8"]  
  max: 40
  enforce: "users"

faillock:
  deny: 5
  unlock_time: 900
  even_deny_root: true
  audit: true

login_defs:
  PASS_MAX_DAYS: 365
  PASS_MIN_DAYS: 1
  PASS_WARN_AGE: 7
  LOGIN_RETRIES: 5
  UMASK: "027"
  FAILLOG_ENAB: "yes"
  LOG_OK_LOGINS: "yes"
  LOG_UNKFAIL_ENAB: "yes"  

blacklist_filesystems:
  - cramfs
  - freevxfs
  - jffs2
  - hfs
  - hfsplus
  - udf
