---
services:
  nexus:
    image: sonatype/nexus3:3.87.0
    container_name: nexus
    hostname: nexus
    restart: unless-stopped
    volumes:
      - nexus_data:/nexus-data
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus.rule=Host(`nexus.amirkolahi.ir`)"
      - "traefik.http.routers.nexus.entrypoints=websecure"
      - "traefik.http.routers.nexus.tls.certresolver=letsencrypt"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
      - "traefik.http.routers.nexus-http.rule=Host(`nexus.amirkolahi.ir`)"
      - "traefik.http.routers.nexus-http.entrypoints=web"
      - "traefik.http.routers.nexus-http.middlewares=nexus-https-redirect"
      - "traefik.http.middlewares.hsts.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hsts.headers.stsPreload=true"
      - "traefik.http.middlewares.nexus-https-redirect.redirectscheme.scheme=https"

networks:
  traefik_net:
    external: true

volumes:
  nexus_data:
    name: nexus_data
