---
services:
  nexus:
    image: sonatype/nexus3:3.87.0
    container_name: nexus
    hostname: nexus
    restart: unless-stopped
    volumes:
      - nexus_data:/nexus-data
    networks:
      - traefik_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus.rule=Host(`nexus.amirkolahi.ir`)"
      - "traefik.http.routers.nexus.entrypoints=websecure"
      - "traefik.http.routers.nexus.tls.certresolver=letsencrypt"
      - "traefik.http.routers.nexus.service=nexus" 
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
      - "traefik.http.routers.nexus-http.rule=Host(`nexus.amirkolahi.ir`)"
      - "traefik.http.routers.nexus-http.entrypoints=web"
      - "traefik.http.routers.nexus-http.middlewares=nexus-https-redirect"
      - "traefik.http.routers.nexus-http.service=nexus" 
      - "traefik.http.middlewares.nexus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.hub.rule=Host(`docker.amirkolahi.ir`)"
      - "traefik.http.routers.hub.entrypoints=websecure"
      - "traefik.http.routers.hub.tls.certresolver=letsencrypt"
      - "traefik.http.routers.hub.service=hub" 
      - "traefik.http.services.hub.loadbalancer.server.port=8083"
      - "traefik.http.routers.hub-http.rule=Host(`docker.amirkolahi.ir`)"
      - "traefik.http.routers.hub-http.entrypoints=web"
      - "traefik.http.routers.hub-http.middlewares=hub-https-redirect"
      - "traefik.http.routers.hub-http.service=hub" 
      - "traefik.http.middlewares.hub-https-redirect.redirectscheme.scheme=https"


networks:
  traefik_net:
    external: true

volumes:
  nexus_data:
    name: nexus_data
