---
sshd_config:
  PermitRootLogin: "no"
  Port: "2222"
  PubkeyAuthentication: "yes"
  PasswordAuthentication: "no"
  AllowAgentForwarding: "no"
  AllowTcpForwarding: "no"
  X11Forwarding: "no"
  Banner: "/etc/issue"
  PrintMotd: "no"
  TCPKeepAlive: "no"
  Compression: "no"
  ClientAliveCountMax: "2"
  AllowUsers: "ubuntu  root"
  AllowGroups: "ubuntu root"
  UsePAM: "yes"
  ChallengeResponseAuthentication: "no"
  MaxAuthTries: "3"
  MaxSessions: "2"
  LogLevel: "VERBOSE"
  ListenAddress: "0.0.0.0"
  AuthenticationMethods: "publickey,keyboard-interactive"
  KexAlgorithms: "curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256"
  Ciphers: "chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com"
  MACs: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com"
packages:
  - sysstat
  - wget
  - git
  - vim
  - nano
  - bash-completion
  - curl
  - htop
  - iftop
  - jq
  - ncdu
  - unzip
  - net-tools
  - dnsutils
  - iotop
  - ntp
  - fail2ban
  - software-properties-common
  - apache2-utils
  - tcpdump
  - telnet
  - axel
  - iptables-persistent
  - ntp
  - auditd
  - libpwquality-common
  - cracklib-runtime

