---
sshd_port: 22
sshd_host_keys:
  - /etc/ssh/ssh_host_ed25519_key
  - /etc/ssh/ssh_host_rsa_key

sshd_permit_root_login: "yes"
sshd_password_authentication: "no"
sshd_kbd_interactive_authentication: "no"
sshd_challenge_response_authentication: "no"
sshd_pubkey_authentication: "yes"

sshd_x11_forwarding: "no"
sshd_allow_agent_forwarding: "no"
sshd_allow_tcp_forwarding: "no"
sshd_permit_tunnel: "no"
sshd_allow_stream_local_forwarding: "no"
sshd_permit_user_environment: "no"

sshd_client_alive_interval: 600
sshd_client_alive_count_max: 3
sshd_login_grace_time: 30
sshd_max_auth_tries: 3
sshd_max_sessions: 10
sshd_use_pam: "yes"
sshd_print_motd: "no"
sshd_print_last_log: "yes"
sshd_use_dns: "no"

# Strong crypto (aligned with DevSec)
sshd_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

sshd_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256

sshd_kex:
  - curve25519-sha256
  - curve25519-sha256@libssh.org
  - ecdh-sha2-nistp256
  - ecdh-sha2-nistp384
  - ecdh-sha2-nistp521
  - diffie-hellman-group16-sha512
  - diffie-hellman-group18-sha512

sshd_syslog_facility: AUTHPRIV
sshd_log_level: VERBOSE
sshd_revoked_keys_file: /etc/ssh/revoked_keys
sshd_subsystem_sftp: internal-sftp