---
services:
  redis-master:
    image: bitnamilegacy/redis:8.2.0
    hostname: redis-master
    networks:
      - redis_net
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master

  redis-slave:
    image: bitnamilegacy/redis:8.2.0
    hostname: redis-slave
    networks:
      - redis_net
    depends_on:
      - redis-master
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master

  redis-sentinel:
    image: bitnamilegacy/redis-sentinel:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
      - REDIS_SENTINEL_QUORUM=1
      - REDIS_SENTINEL_FAILOVER_TIMEOUT=3000
      - REDIS_SENTINEL_ANNOUNCE_HOSTNAMES=yes
    deploy:
      mode: global
    depends_on:
      - redis-master
    networks:
      - redis_net

  proxy:
    image: haproxy:lts
    hostname: redis
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - redis_net
      - app_net
    depends_on:
      - redis-sentinel
    deploy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.haproxy.rule=Host(`haproxy.amirkolahi.ir`)"
      - "traefik.http.routers.haproxy.entrypoints=websecure"
      - "traefik.http.routers.haproxy.tls.certresolver=letsencrypt"
      - "traefik.http.services.haproxy.loadbalancer.server.port=80"
      - "traefik.http.routers.haproxy-http.rule=Host(`haproxy.amirkolahi.ir`)"
      - "traefik.http.routers.haproxy-http.entrypoints=web"
      - "traefik.http.routers.haproxy-http.middlewares=haproxy-https-redirect"
      - "traefik.http.middlewares.hsts.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.hsts.headers.stsPreload=true"
      - "traefik.http.middlewares.haproxy-https-redirect.redirectscheme.scheme=https"

networks:
  redis_net:
    name: redis_net
    driver: bridge
    external: false