services:
  runner:
    image: gitlab/gitlab-runner:alpine3.21-bleeding
    restart: always
    container_name: runner
    hostname: runner
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "gitlab-runner:/etc/gitlab-runner"

volumes:
  gitlab-runner:
    name: gitlab-runner