---
project_path: "/opt/projects/nexus"
nexus_main_url: "https://nexus.amirkolahi.ir"

nexus_username: "admin"
nexus_password: "amirkolahi!@#" 

docker_proxies:
  - name: "dockerhub-repo"
    remote_url: "https://registry-1.docker.io"
    port: 1404
    index_type: "HUB"
  
  - name: "gcr-proxy"
    remote_url: "https://gcr.io"
    port: 1405 
    index_type: "REGISTRY_V2"
  
  - name: "quay-proxy"
    remote_url: "https://quay.io"
    port: 8084
    index_type: "REGISTRY_V2"