---
project_path: "/opt/projects/nexus"
nexus_main_url: "https://nexus.amirkolahi.ir"

docker_proxies:

  - name: "gcr-proxy"
    remote_url: "https://gcr.io"
    port: 1405 
    index_type: "REGISTRY_V2"
  
  - name: "quay-proxy"
    remote_url: "https://quay.io"
    port: 8084
    index_type: "REGISTRY_V2"